FROM node:18.13
RUN apt-get update -y
RUN apt-get install zip unzip curl vim wget docker.io  -y
RUN apt-get update -y
WORKDIR /app
COPY package.json /app
RUN npm install
COPY server.js /app
CMD node server.js